version: 2

defaults: &defaults
  working_directory: ~/detect-next-version
  docker:
    - image: circleci/node:8@sha256:257fdc7e2949a9576e1a96364e0428d461d0505167c70dcc3e6c3825ce8a6557

restore_modules_cache: &restore_modules_cache
  restore_cache:
    keys:
    - detect-next-version-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - detect-next-version-


jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Installing Dependencies
          command: yarn install
      - save_cache:
          key: detect-next-version-{{ checksum "yarn.lock" }}
          paths: node_modules
      - run:
          name: Remove node_modules to cleanup workspace
          command: rm -rf node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Running tests and checks
          command: yarn test
      - run:
          name: Sending test coverage to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Creating distributable files
          command: echo ok
      - store_artifacts:
          path: dist
          destination: detect-next-version

  publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Trying to deploy
          command: yarn hela release

workflows:
  version: 2
  automated:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
          context: org-global
